# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pavlos/research/PROJECTS/neighborjoining_repeated/neighborjoining

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pavlos/research/PROJECTS/neighborjoining_repeated/neighborjoining

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pavlos/research/PROJECTS/neighborjoining_repeated/neighborjoining/CMakeFiles /home/pavlos/research/PROJECTS/neighborjoining_repeated/neighborjoining//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pavlos/research/PROJECTS/neighborjoining_repeated/neighborjoining/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neighborjoining-linux

# Build rule for target.
neighborjoining-linux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neighborjoining-linux
.PHONY : neighborjoining-linux

# fast build rule for target.
neighborjoining-linux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/build
.PHONY : neighborjoining-linux/fast

include/levenshtein/levenshtein.o: include/levenshtein/levenshtein.c.o
.PHONY : include/levenshtein/levenshtein.o

# target to build an object file
include/levenshtein/levenshtein.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/include/levenshtein/levenshtein.c.o
.PHONY : include/levenshtein/levenshtein.c.o

include/levenshtein/levenshtein.i: include/levenshtein/levenshtein.c.i
.PHONY : include/levenshtein/levenshtein.i

# target to preprocess a source file
include/levenshtein/levenshtein.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/include/levenshtein/levenshtein.c.i
.PHONY : include/levenshtein/levenshtein.c.i

include/levenshtein/levenshtein.s: include/levenshtein/levenshtein.c.s
.PHONY : include/levenshtein/levenshtein.s

# target to generate assembly for a file
include/levenshtein/levenshtein.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/include/levenshtein/levenshtein.c.s
.PHONY : include/levenshtein/levenshtein.c.s

src/binary_tree.o: src/binary_tree.c.o
.PHONY : src/binary_tree.o

# target to build an object file
src/binary_tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/binary_tree.c.o
.PHONY : src/binary_tree.c.o

src/binary_tree.i: src/binary_tree.c.i
.PHONY : src/binary_tree.i

# target to preprocess a source file
src/binary_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/binary_tree.c.i
.PHONY : src/binary_tree.c.i

src/binary_tree.s: src/binary_tree.c.s
.PHONY : src/binary_tree.s

# target to generate assembly for a file
src/binary_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/binary_tree.c.s
.PHONY : src/binary_tree.c.s

src/clusters_matrix.o: src/clusters_matrix.c.o
.PHONY : src/clusters_matrix.o

# target to build an object file
src/clusters_matrix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/clusters_matrix.c.o
.PHONY : src/clusters_matrix.c.o

src/clusters_matrix.i: src/clusters_matrix.c.i
.PHONY : src/clusters_matrix.i

# target to preprocess a source file
src/clusters_matrix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/clusters_matrix.c.i
.PHONY : src/clusters_matrix.c.i

src/clusters_matrix.s: src/clusters_matrix.c.s
.PHONY : src/clusters_matrix.s

# target to generate assembly for a file
src/clusters_matrix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/clusters_matrix.c.s
.PHONY : src/clusters_matrix.c.s

src/cmdline.o: src/cmdline.c.o
.PHONY : src/cmdline.o

# target to build an object file
src/cmdline.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/cmdline.c.o
.PHONY : src/cmdline.c.o

src/cmdline.i: src/cmdline.c.i
.PHONY : src/cmdline.i

# target to preprocess a source file
src/cmdline.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/cmdline.c.i
.PHONY : src/cmdline.c.i

src/cmdline.s: src/cmdline.c.s
.PHONY : src/cmdline.s

# target to generate assembly for a file
src/cmdline.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/cmdline.c.s
.PHONY : src/cmdline.c.s

src/fasta_parser.o: src/fasta_parser.c.o
.PHONY : src/fasta_parser.o

# target to build an object file
src/fasta_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/fasta_parser.c.o
.PHONY : src/fasta_parser.c.o

src/fasta_parser.i: src/fasta_parser.c.i
.PHONY : src/fasta_parser.i

# target to preprocess a source file
src/fasta_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/fasta_parser.c.i
.PHONY : src/fasta_parser.c.i

src/fasta_parser.s: src/fasta_parser.c.s
.PHONY : src/fasta_parser.s

# target to generate assembly for a file
src/fasta_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/fasta_parser.c.s
.PHONY : src/fasta_parser.c.s

src/neighborjoining.o: src/neighborjoining.c.o
.PHONY : src/neighborjoining.o

# target to build an object file
src/neighborjoining.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/neighborjoining.c.o
.PHONY : src/neighborjoining.c.o

src/neighborjoining.i: src/neighborjoining.c.i
.PHONY : src/neighborjoining.i

# target to preprocess a source file
src/neighborjoining.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/neighborjoining.c.i
.PHONY : src/neighborjoining.c.i

src/neighborjoining.s: src/neighborjoining.c.s
.PHONY : src/neighborjoining.s

# target to generate assembly for a file
src/neighborjoining.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neighborjoining-linux.dir/build.make CMakeFiles/neighborjoining-linux.dir/src/neighborjoining.c.s
.PHONY : src/neighborjoining.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... neighborjoining-linux"
	@echo "... include/levenshtein/levenshtein.o"
	@echo "... include/levenshtein/levenshtein.i"
	@echo "... include/levenshtein/levenshtein.s"
	@echo "... src/binary_tree.o"
	@echo "... src/binary_tree.i"
	@echo "... src/binary_tree.s"
	@echo "... src/clusters_matrix.o"
	@echo "... src/clusters_matrix.i"
	@echo "... src/clusters_matrix.s"
	@echo "... src/cmdline.o"
	@echo "... src/cmdline.i"
	@echo "... src/cmdline.s"
	@echo "... src/fasta_parser.o"
	@echo "... src/fasta_parser.i"
	@echo "... src/fasta_parser.s"
	@echo "... src/neighborjoining.o"
	@echo "... src/neighborjoining.i"
	@echo "... src/neighborjoining.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

